Repository SanaaTeam/Novix, pull requests merged in 2025-08, with the labels that each got.

#445 refactor fix data loading delay
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/ActorViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/series/SeriesViewModel.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/genreTvShows/GenreTvShowsViewModelTest.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsViewModelTest.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/series/SeriesViewModelTest.kt
Labels: needs review

#467 Feature/Create Custom List Domain
  domain/vod/src/main/java/repository/SavedListRepository.kt
  domain/vod/src/main/java/usecase/custom_list/ManageSavedListItemsUseCase.kt
  domain/vod/src/main/java/usecase/custom_list/ManageSavedListsUseCase.kt
  domain/vod/src/main/java/usecase/custom_list/custom_list_param/SavedList.kt
  domain/vod/src/test/java/usecase/custom_list/ManageSavedListItemsUseCaseTest.kt
  domain/vod/src/test/java/usecase/custom_list/ManageSavedListsUseCaseTest.kt
Labels: needs review

#517 On boarding screen
  app/build.gradle.kts
  feature/home/presentation/src/main/res/values-ar/strings.xml
  feature/home/presentation/src/main/res/values/strings.xml
  feature/onboarding/api/.gitignore
  feature/onboarding/api/build.gradle.kts
  feature/onboarding/api/consumer-rules.pro
  feature/onboarding/api/proguard-rules.pro
  feature/onboarding/api/src/androidTest/java/com/sanaa/api/ExampleInstrumentedTest.kt
  feature/onboarding/api/src/main/AndroidManifest.xml
  feature/onboarding/api/src/main/java/com/sanaa/api/OnboardingApi.kt
  feature/onboarding/api/src/test/java/com/sanaa/api/ExampleUnitTest.kt
  feature/onboarding/presentation/.gitignore
  feature/onboarding/presentation/build.gradle.kts
  feature/onboarding/presentation/consumer-rules.pro
  feature/onboarding/presentation/proguard-rules.pro
  feature/onboarding/presentation/src/androidTest/java/com/sanaa/presentation/ExampleInstrumentedTest.kt
  feature/onboarding/presentation/src/main/AndroidManifest.xml
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/component/CircleShapeBlur.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/component/DialogContainer.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/component/OnBoardingPageContentItem.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/onbordingBase/BaseViewModel.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingEffect.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingInteractionsListener.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingScreen.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingUiState.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingViewModel.kt
  feature/onboarding/presentation/src/main/res/drawable/icon_left_arrow.xml
  feature/onboarding/presentation/src/main/res/drawable/icon_right_arrow.xml
  feature/onboarding/presentation/src/main/res/drawable/onboarding_1.png
  feature/onboarding/presentation/src/main/res/drawable/onboarding_2.png
  feature/onboarding/presentation/src/main/res/drawable/onboarding_3.png
  feature/onboarding/presentation/src/main/res/values-ar/strings_ar.xml
  feature/onboarding/presentation/src/main/res/values/strings.xml
  feature/onboarding/presentation/src/test/java/com/sanaa/presentation/ExampleUnitTest.kt
  feature/onboarding/presentation/src/test/java/com/sanaa/presentation/OnboardingViewModelTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: needs review

#563 refactor playlist details screen
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreen.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreenViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlistDetails/components/EmptyListScreen.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlistDetails/components/SavedDetailsListSectionContent.kt
  feature/playlists/presentation/src/main/res/drawable/no_items.png
  feature/playlists/presentation/src/main/res/values-ar/strings.xml
  feature/playlists/presentation/src/main/res/values/strings.xml
  feature/playlists/presentation/src/test/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreenViewModelTest.kt
Labels: needs review

#578 Replace webp images for category with smaller versions
  feature/category/presentation/src/main/res/drawable/movie_action.webp
  feature/category/presentation/src/main/res/drawable/movie_adventure.webp
  feature/category/presentation/src/main/res/drawable/movie_animation.webp
  feature/category/presentation/src/main/res/drawable/movie_comedy.webp
  feature/category/presentation/src/main/res/drawable/movie_crime.webp
  feature/category/presentation/src/main/res/drawable/movie_documenteray.webp
  feature/category/presentation/src/main/res/drawable/movie_family.webp
  feature/category/presentation/src/main/res/drawable/movie_fantasy.webp
  feature/category/presentation/src/main/res/drawable/movie_history.webp
  feature/category/presentation/src/main/res/drawable/movie_horror.webp
  feature/category/presentation/src/main/res/drawable/movie_music.webp
  feature/category/presentation/src/main/res/drawable/movie_mystery.webp
  feature/category/presentation/src/main/res/drawable/movie_romance.webp
  feature/category/presentation/src/main/res/drawable/movie_science_fiction.webp
  feature/category/presentation/src/main/res/drawable/movie_threiller.webp
  feature/category/presentation/src/main/res/drawable/movie_tv_movie.webp
  feature/category/presentation/src/main/res/drawable/movie_war.webp
  feature/category/presentation/src/main/res/drawable/movie_western.webp
  feature/category/presentation/src/main/res/drawable/tv_action_adventure.webp
  feature/category/presentation/src/main/res/drawable/tv_animation.webp
  feature/category/presentation/src/main/res/drawable/tv_kids.webp
  feature/category/presentation/src/main/res/drawable/tv_news.webp
  feature/category/presentation/src/main/res/drawable/tv_reality.webp
  feature/category/presentation/src/main/res/drawable/tv_sci_fi_fantasy.webp
  feature/category/presentation/src/main/res/drawable/tv_soap.webp
  feature/category/presentation/src/main/res/drawable/tv_talk.webp
Labels: needs review

#590 Refactor/baseviewmodels update state funcation
  app/src/main/java/com/sanaa/novix/main/MainViewModel.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/api/AuthenticationViewModel.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/login/LoginViewModel.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/login_base/BaseViewModel.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/welcome/WelcomeViewModel.kt
  feature/authentication/presentation/src/test/java/com/sanaa/presentation/screen/login_base/BaseViewModelTest.kt
  feature/category/presentation/src/main/java/com/sanaa/presentation/categoryBase/BaseViewModel.kt
  feature/category/presentation/src/main/java/com/sanaa/presentation/screen/CategoriesScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/BaseViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/app/NovixAppViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/bottomsheet/addEditBookmark/AddBookmarkListViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/bottomsheet/saveToListBottomsheet/SaveToListViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/mediaTabScreen/topRatingScreen/TopRatedMediaScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/mediaTabScreen/watchingHistoryScreen/WatchingMediaHistoryScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/trendingMediaScreen/trendingMoviesScreen/TrendingMoviesScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/trendingMediaScreen/trendingTvShowScreen/TrendingTvShowsScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/trendingPeopleScreen/TrendingPeopleViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/state/mapper/MediaMapper.kt
  feature/home/presentation/src/test/java/com/sanaa/presentation/bottomsheet/addEditBookmark/AddBookmarkListViewModelTest.kt
  feature/home/presentation/src/test/java/com/sanaa/presentation/bottomsheet/saveToListBottomsheet/SaveToListViewModelTest.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/bottomsheets/addEditBookmark/AddBookmarkViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/bottomsheets/saveToListBottomsheet/SaveToListsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/details_base/BaseViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/main/MediaDetailsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/ActorViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreMovies/GenreMoviesViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreTvShows/GenreTvShowsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/review/ReviewViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/series/SeriesViewModel.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsViewModelTest.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/series/SeriesViewModelTest.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/onbordingBase/BaseViewModel.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/bottomsheets/addEditBookmark/AddBookmarkListViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/bottomsheets/deletebottomsheet/DeleteListViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/savedBase/BaseViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlist/PlayListScreenViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreenViewModel.kt
  feature/playlists/presentation/src/test/java/com/sanaa/presentation/screen/playlistDetails/PlayListScreenViewModelTest.kt
  feature/playlists/presentation/src/test/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreenViewModelTest.kt
  feature/search/presentation/src/main/java/com/sanaa/presentation/base/BaseViewModel.kt
  feature/search/presentation/src/main/java/com/sanaa/presentation/bottomsheets/addEditBookmark/AddBookmarksListViewModel.kt
  feature/search/presentation/src/main/java/com/sanaa/presentation/bottomsheets/saveToListBottomsheet/SavetoListViewModel.kt
  feature/search/presentation/src/main/java/com/sanaa/presentation/screen/SearchViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/MyProfileViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/profileBase/BaseViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/bottomsheet/addEditBookmark/AddBookmarkListViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/bottomsheet/saveToBottomSheet/SaveToListViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/myAccount/MyAccountScreenViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/myRating/MyRatingScreenViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/screen/watchingHistory/WatchingHistoryViewModel.kt
  feature/user_profile/presentation/src/test/java/com/sanaa/presentation/myAccount/MyAccountScreenViewModelTest.kt
  feature/user_profile/presentation/src/test/java/com/sanaa/presentation/myAccount/MyRatingScreenViewModelTest.kt
  feature/user_profile/presentation/src/test/java/com/sanaa/presentation/viewmodel/WatchingHistoryViewModelTest.kt
  gradle/libs.versions.toml
Labels: needs review

#588 refactor viewmodel executables to handle the states by referenced fun…
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt
Labels: needs review

#598 Refactor/actor screen
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/navigation/DetailsNavHost.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/navigation/detailsRouts.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/ActorViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/componants/MediaSection.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/ActorGalleryScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/ActorScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/TopMoviesScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/TopSeriesScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/series/SeriesScreen.kt
  feature/media_details/presentation/src/main/res/drawable/birthday_cake.xml
  feature/media_details/presentation/src/main/res/drawable/location.xml
  feature/media_details/presentation/src/main/res/values/strings.xml
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/actors/ActorViewModelTest.kt
Labels: needs review

#601 Refactor/domain exceptions
  data/repositories/identity/src/main/java/com/sanaa/identity/util/wrapApiCall.kt
  data/repositories/vod/src/main/java/com/sanaa/vod/repository/HistoryRepositoryImpl.kt
  data/repositories/vod/src/main/java/com/sanaa/vod/util/safeCall.kt
  data/repositories/vod/src/test/java/com/sanaa/vod/repository/ActorRepositoryImplTest.kt
  data/repositories/vod/src/test/java/com/sanaa/vod/repository/HistoryRepositoryImplTest.kt
  data/repositories/vod/src/test/java/com/sanaa/vod/repository/MovieRepositoryImplTest.kt
  data/repositories/vod/src/test/java/com/sanaa/vod/repository/SearchRepositoryImplTest.kt
  data/repositories/vod/src/test/java/com/sanaa/vod/repository/TvShowRepositoryImplTest.kt
  data/repositories/vod/src/test/java/com/sanaa/vod/util/SafeCallKtTest.kt
  domain/identity/src/main/java/exceptions/exceptions.kt
  domain/vod/src/main/java/exceptions/Exceptions.kt
  domain/vod/src/main/java/exceptions/exceptions.kt
  domain/vod/src/test/java/usecase/custom_list/ManageSavedListsUseCaseTest.kt
  domain/vod/src/test/java/usecase/details/ManageActorUseCaseTest.kt
  domain/vod/src/test/java/usecase/details/ManageMovieUseCaseTest.kt
  domain/vod/src/test/java/usecase/details/ManageTvSeriesUseCaseTest.kt
  domain/vod/src/test/java/usecase/search/ManageHistoryUseCaseTest.kt
  domain/vod/src/test/java/usecase/search/ManageRecentViewedUseCaseTest.kt
  domain/vod/src/test/java/usecase/search/SearchUseCaseTest.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/login/LoginViewModel.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/login_base/BaseViewModel.kt
  feature/authentication/presentation/src/test/java/com/sanaa/presentation/screen/login/LoginViewModelTest.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/BaseViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/base/BasePagingSourceForHome.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/bottomsheet/addEditBookmark/AddBookmarkListViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/bottomsheet/saveToListBottomsheet/SaveToListViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/homeScreen/HomeScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/mediaTabScreen/topRatingScreen/TopRatedMediaScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/mediaTabScreen/watchingHistoryScreen/WatchingMediaHistoryScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/trendingMediaScreen/trendingMoviesScreen/TrendingMoviesScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/trendingMediaScreen/trendingTvShowScreen/TrendingTvShowsScreenViewModel.kt
  feature/home/presentation/src/main/java/com/sanaa/presentation/screen/trendingPeopleScreen/TrendingPeopleViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/bottomsheets/addEditBookmark/AddBookmarkViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/bottomsheets/saveToListBottomsheet/SaveToListsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/details_base/BasePagingSource.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/details_base/BaseViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreMovies/GenreMoviesViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreTvShows/GenreTvShowsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/review/ReviewViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/series/SeriesViewModel.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/api/OnBoardingApiImpl.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/component/DialogContainer.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/onbordingBase/BaseViewModel.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingEffect.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingScreen.kt
  feature/onboarding/presentation/src/main/java/com/sanaa/presentation/screen/OnboardingViewModel.kt
  feature/onboarding/presentation/src/test/java/com/sanaa/presentation/OnboardingViewModelTest.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/bottomsheets/addEditBookmark/AddBookmarkListViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/bottomsheets/deletebottomsheet/DeleteListViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/savedBase/BaseViewModel.kt
  feature/playlists/presentation/src/main/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreenViewModel.kt
  feature/playlists/presentation/src/test/java/com/sanaa/presentation/screen/playlistDetails/PlaylistDetailsScreenViewModelTest.kt
  feature/search/presentation/src/main/java/com/sanaa/presentation/base/BaseViewModel.kt
  feature/search/presentation/src/main/java/com/sanaa/presentation/bottomsheets/saveToListBottomsheet/SaveToListViewModel.kt
  feature/user_profile/presentation/src/main/java/com/sanaa/presentation/profileBase/BaseViewModel.kt
Labels: In-Progress

#620 Convert onboarding images from PNG to WEBP
  feature/onboarding/presentation/src/main/res/drawable/onboarding_1.png
  feature/onboarding/presentation/src/main/res/drawable/onboarding_1.webp
  feature/onboarding/presentation/src/main/res/drawable/onboarding_2.png
  feature/onboarding/presentation/src/main/res/drawable/onboarding_2.webp
  feature/onboarding/presentation/src/main/res/drawable/onboarding_3.png
  feature/onboarding/presentation/src/main/res/drawable/onboarding_3.webp
Labels: needs review

#599 Refactor/serialize route navigation
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/navigation/DetailsNavHost.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/navigation/detailsRouts.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/ActorScreenViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/ActorGalleryScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/ActorScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/TopMoviesScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/actor/screen/TopShowsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreMovies/GenreMoviesScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreMovies/GenreMoviesViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreTvShows/GenreTvShowsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/genreTvShows/GenreTvShowsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/movieDetails/MovieDetailsViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/review/ReviewScreenViewModel.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/tvShow/TvShowScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/tvShow/TvShowScreenViewModel.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/actors/ActorViewModelTest.kt
Labels: needs review

#637 refactor episode
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsEffects.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsInteractionListener.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreen.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenUiState.kt
  feature/media_details/presentation/src/main/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenViewModel.kt
  feature/media_details/presentation/src/test/java/com/sanaa/presentation/screen/episodeDetails/EpisodeDetailsScreenViewModelTest.kt
Labels: In-Progress, needs review

#664 handle error in welcome screen
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/welcome/WelcomeScreen.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/welcome/WelcomeScreenInteractionListener.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/welcome/WelcomeScreenUiState.kt
  feature/authentication/presentation/src/main/java/com/sanaa/presentation/screen/welcome/WelcomeViewModel.kt
  feature/authentication/presentation/src/test/java/com/sanaa/presentation/screen/welcome/WelcomeViewModelTest.kt
Labels: needs review

#676 Feature/read me
  README.md
Labels: needs review

#682 Fix some issues in tv app
  README.md
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/category/CategoriesScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/category/compnents/CategoriesGrid.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/category/compnents/CategoryCard.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/genreMovies/GenreMoviesScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/genreTvShows/GenreTvShowsScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/home/HomeScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/mediaDetails/actorScreen/ActorScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/mediaDetails/components/CastSlider.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/mediaDetails/components/SimilarMoviesSlider.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/mediaDetails/components/TopMoviesSlider.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/mediaDetails/components/TopTvShowsSlider.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/myAccount/MyAccountScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/searchScreen/SearchScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/searchScreen/componants/FocusableMediaCard.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/searchScreen/componants/TvMediaPosterCard.kt
  tvapp/src/main/java/com/sanaa/tvapp/util/modifier/modifier.kt
Labels: needs review

#745 prepare password eye to show\hide password
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/login/LoginScreen.kt
  tvapp/src/main/java/com/sanaa/tvapp/presentation/screens/login/components/PasswordInput.kt
  tvapp/src/main/res/values-ar/strings.xml
  tvapp/src/main/res/values/strings.xml
Labels: needs review
